version: '3.4'

services:
  flask_app:
    image: trafficpubsub
    ports:
      - "5002:5002"
    networks:
      - traffic_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  
networks:
  traffic_network:
    driver: bridge
